export const SUBMIT_REVIEW_LOADING = "SUBMIT_REVIEW_LOADING";
export const SUBMIT_REVIEW_CREATE = "SUBMIT_REVIEW_CREATE";
export const SUBMIT_REVIEW_ADD_UUI = "SUBMIT_REVIEW_ADD_UUI";
export const SUBMIT_REVIEW_SELECT = "SUBMIT_REVIEW_SELECT";
export const SUBMIT_REVIEW_DELETE_ROW = "SUBMIT_REVIEW_DELETE_ROW";

export const SUBMIT_REVIEW_ADD_COMPARATORS_UPLOAD =
  "SUBMIT_REVIEW_ADD_COMPARATORS_UPLOAD";
