export const OPTIONS_LOADING = "OPTIONS_LOADING";
export const OPTIONS_CREATE = "OPTIONS_CREATE";
export const OPTIONS_SELECT = "OPTIONS_SELECT";
export const OPTIONS_DELETE_ROW = "OPTIONS_DELETE_ROW";
