version: "3.9"

services:
  web:
    image: nginx
    volumes:
      - ../build:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    ports:
      - 3000:80
